//
// Generated file, do not edit! Created by opp_msgc 4.3 from myHeader.msg.
//

#ifndef _MYHEADER_M_H_
#define _MYHEADER_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>myHeader.msg</tt> by opp_msgc.
 * <pre>
 * packet MyHeader {
 *     
 *     string name;
 *     int ID;
 *     int year;
 *     
 * }
 * </pre>
 */
class MyHeader : public ::cPacket
{
  protected:
    opp_string name_var;
    int ID_var;
    int year_var;

  private:
    void copy(const MyHeader& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MyHeader&);

  public:
    MyHeader(const char *name=NULL, int kind=0);
    MyHeader(const MyHeader& other);
    virtual ~MyHeader();
    MyHeader& operator=(const MyHeader& other);
    virtual MyHeader *dup() const {return new MyHeader(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getName() const;
    virtual void setName(const char * name);
    virtual int getID() const;
    virtual void setID(int ID);
    virtual int getYear() const;
    virtual void setYear(int year);
};

inline void doPacking(cCommBuffer *b, MyHeader& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MyHeader& obj) {obj.parsimUnpack(b);}


#endif // _MYHEADER_M_H_
